[server]
port = 80
export STREAMLIT_SERVER_PORT=80
export STREAMLIT_SERVER_COOKIE_SECRET=dontforgottochangeme
streamlit run MOVIA/API/v1/main.py --server.port 80
streamlit run MOVIA/app.py --server.port 82
